# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginCodi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_LoginCodi(object):
    def setupUi(self, Dialog_LoginCodi):
        Dialog_LoginCodi.setObjectName("Dialog_LoginCodi")
        Dialog_LoginCodi.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_LoginCodi.resize(532, 289)
        Dialog_LoginCodi.setMaximumSize(QtCore.QSize(16777215, 417))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_LoginCodi)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon = QtWidgets.QLabel(Dialog_LoginCodi)
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../../../../.designer/backup/codi.png"))
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setWordWrap(False)
        self.icon.setObjectName("icon")
        self.verticalLayout.addWidget(self.icon)
        self.label_account = QtWidgets.QLabel(Dialog_LoginCodi)
        self.label_account.setObjectName("label_account")
        self.verticalLayout.addWidget(self.label_account)
        self.lineEdit_account = QtWidgets.QLineEdit(Dialog_LoginCodi)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.verticalLayout.addWidget(self.lineEdit_account)
        self.label_2 = QtWidgets.QLabel(Dialog_LoginCodi)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog_LoginCodi)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.pushButton_login = QtWidgets.QPushButton(Dialog_LoginCodi)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout.addWidget(self.pushButton_login)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_LoginCodi)
        QtCore.QMetaObject.connectSlotsByName(Dialog_LoginCodi)

    def retranslateUi(self, Dialog_LoginCodi):
        _translate = QtCore.QCoreApplication.translate
        Dialog_LoginCodi.setWindowTitle(_translate("Dialog_LoginCodi", "Login CodiMD"))
        self.label_account.setText(_translate("Dialog_LoginCodi", "CodiMD account"))
        self.lineEdit_account.setPlaceholderText(_translate("Dialog_LoginCodi", "Account..."))
        self.label_2.setText(_translate("Dialog_LoginCodi", "Password"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog_LoginCodi", "Password..."))
        self.pushButton_login.setText(_translate("Dialog_LoginCodi", "Login"))
