# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentListSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_StudentList(object):
    def setupUi(self, Dialog_StudentList):
        Dialog_StudentList.setObjectName("Dialog_StudentList")
        Dialog_StudentList.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_StudentList.resize(539, 417)
        Dialog_StudentList.setMaximumSize(QtCore.QSize(16777215, 417))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_StudentList)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_LoadSLFile = QtWidgets.QPushButton(Dialog_StudentList)
        self.pushButton_LoadSLFile.setObjectName("pushButton_LoadSLFile")
        self.horizontalLayout.addWidget(self.pushButton_LoadSLFile)
        self.pushButton_SLComfirm = QtWidgets.QPushButton(Dialog_StudentList)
        self.pushButton_SLComfirm.setObjectName("pushButton_SLComfirm")
        self.horizontalLayout.addWidget(self.pushButton_SLComfirm)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tableView_SL = QtWidgets.QTableView(Dialog_StudentList)
        self.tableView_SL.setObjectName("tableView_SL")
        self.gridLayout_2.addWidget(self.tableView_SL, 0, 0, 1, 1)

        self.retranslateUi(Dialog_StudentList)
        QtCore.QMetaObject.connectSlotsByName(Dialog_StudentList)

    def retranslateUi(self, Dialog_StudentList):
        _translate = QtCore.QCoreApplication.translate
        Dialog_StudentList.setWindowTitle(_translate("Dialog_StudentList", "Choose Student list file..."))
        self.pushButton_LoadSLFile.setText(_translate("Dialog_StudentList", "Load Student List File (.csv)"))
        self.pushButton_SLComfirm.setText(_translate("Dialog_StudentList", "OK"))
