runtime: php81

env_variables:
  APP_DEBUG: true
  LOG_CHANNEL: stderr
  APP_STORAGE: /tmp
  INSTANCE_UNIX_SOCKET: /cloudsql/audit-multiple-choice:asia-east1:audit-multiple-choice
  DB_USER: admin
  DB_PASS: Euq]O5FuORbJml0v
  DB_NAME: audit-multiple-choice